stages:
  - test

test:phpunit:
  image: php:8.2
  stage: test
  script:
    - php -v
    - apt-get update -qq
    - apt-get install -yqq libxml2-dev libonig-dev
    - docker-php-ext-install xml mbstring
    - php ./vendor/bin/phpunit --configuration phpunit.xml
